#!/bin/sh
# $./dw-volume up
# $./dw-volume down
# $./dw-volume mute

get_volume() {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

is_mute() {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

send_notification() {
  volume=$(get_volume)
	dunstify -a "changeVolume" -t 8000 -u normal -h string:x-dunst-stack-tag:volume \
	-h int:value:"$volume" "Volume: ${volume}%"
}

send_notification1() {
  volume=$(get_volume)
	dunstify -a "changeVolume" -t 8000 -u normal -h string:x-dunst-stack-tag:volume \
	-h int:value:"$volume" "Volume: ${volume}%"
}

sendmute() {
	dunstify -a "changeVolume" -t 8000 -u normal -h string:x-dunst-stack-tag:volume \
	"Volume: Mute"
}

case $1 in
  up)
	  amixer -q set Master 5%+ unmute & kill -44 $(pidof dwmblocks)
    send_notification
    ;;
  down)
   	  amixer -q set Master 5%- unmute & kill -44 $(pidof dwmblocks)
    send_notification1
    ;;
  mute)
    # Toggle mute
    amixer -q set Master toggle & kill -44 $(pidof dwmblocks)
    if is_mute; then
      sendmute
    else
      send_notification
    fi
    ;;
esac

